### PR TITLE
BUILD 1435359094: Rebuild with buildmanager from add-data-workflow branch

### PR DESCRIPTION
**Pull request by nucivicmachine**

### CODE REVIEW

**Comment by drkloc** [comment]
build only to see why https://travis-ci.org/NuCivic/data_workflow/builds/57102753 is failing

**Comment by acouch** [comment]
QA site created: http://new-build-1435359094.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
Closed for #85 . This branch also doesn't include the changes Frank did in the .travisyml file

**Comment by nucivicmachine** [comment]
QA site created: http://new-build-1435359094.datastarter.qa.nuamsdev.com

**Pull request closed without merging**
