### PR TITLE
Update build.make

### PR DESCRIPTION
**Pull request by acouch**
test update

### CODE REVIEW

**Comment by acouch** [comment]
QA

**Comment by nucivicmachine** [comment]
QA

**Comment by nucivicmachine** [comment]
test comment

**Comment by nucivicmachine** [comment]
QA site created: http://rebuild-nansen-tst.datastarter.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://rebuild-nansen-tst.datastarter.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://rebuild-nansen-tst.datastarter.qa.nuamsdev.com

**Pull request closed without merging**
