### PR TITLE
NuCivic/internal#703 As a Data Contributor, Content Editor and Portal Administrator I want to see easier to understand workbench lists

### PR DESCRIPTION
**Pull request by rhabbachi**
Work done for NuCivic/internal#703
Reworked Workbench pages with new tree-like mockups.
This PR include the work done by @SalahMessaoud on the items count menu-badges.

As per @willieseabrook  instructions:
* Renamed data_workflow to dkan_workflow.
* Moved test file workbench.feature to dkan_workflow/test/features/dkan_workflow.feature

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://703_easier_workbench_lists.datastarter.qa.nuamsdev.com

**Comment by willieseabrook** [comment]
@rhabbachi see below for tasks and bugs

### Code Review

1. Are the following functions still used and needed?

* publishing_workflow_form_alter
* publishing_workflow_rules_action_info
* publishing_workflow_reviewers
* publishing_workflow_block_info_alter

2. Is the following file still needed?

 * publishing_workflow.drush.inc

If we're not totally certain they are required, delete. We can always bring them back if it's a mistake.

### Acceptance Criteria

**Formatting issues for Data Contributor and Content Editor**

needs_review___703_datastarter_devshop_vm

**Incorrect count showing in menu tabs**

my_drafts___703_datastarter_devshop_vm

**Data Contributor is able to access Needs Review Tab and Publish and Reject states**

**Stale Drafts and Stale Reviews do not appear**


**Workbench menu item does not appear for Content Editor and Data Contributor**

***Note this *only* occurs before a second features revert. After features reverting a second time and clearing the cache the menu item appears. Low priority as not really repeatable.

my_workbench___703_datastarter_devshop_vm

**Comment by rhabbachi** [comment]
@willieseabrook committed all the needed changes. Please take a look.

**Comment by willieseabrook** [comment]
@Krista-Nuams @amcnally @federicca 

See below for a test website for the workflow. It is ready, but don't do thorough QA yet. 

Thorough QA is blocked by the roles and permissions reorganisation. There will be a huge amount of permissions changes and also code changes and repository moves, so there is not point in thorough QA as it will need to be repeated after we do that.

http://branch-703-easier-workbench-lists.datastarter.internal.nucivic.build/

User: data contributor
Pass: test

User: content editor
Pass: test

User: portal administrator
Pass: test

**Comment by amcnally** [comment]
1) Log in as portal administrator.
2) Click "Groups"
3) Add group
--ALM Test Group 1
4) Click Save
5) Click Group
6) Click Add people
7) Enter data contributor
--data contributor has been added to the group ALM Test Group 1
8) Enter content editor
9) Check "administrator member"
--content editor has been added to the group ALM Test Group 1
10) Log out
11) Log in as data contributor
12) Inside profile, click "Groups"
--Group membership: ALM Test Group 1
13) Click "Add Dataset" in blue menu bar
--ALM Test Data Set 1
14) In "Groups", select ALM Test Group 1
15) Leave Moderation state at Draft
16) Click Next: Add Data
--ALM Test Resource 1
17) Leave Moderation state at Draft
18) Click Save
19) Issue 1: This screen is pretty confusing...
image
20) Click "Moderate"
21) 
image
22) Repeat steps 13-14
--ALM Test Data Set 2
23) Set Moderation State to Needs Review.
24) Repeat step 16
--ALM Test Resource 2
25) Set Moderation State to Needs Review
26) Click Save
27) Repeat steps 13-14
--ALM Test Data Set 3
28) Set Moderation State to Draft
29) Repeat step 16
--ALM Test Resource 3
30) Set Moderation State to Needs Review
31) Click Save
32) Repeat steps 13-14
--ALM Test Data Set 4
33) Set Moderation State to Needs Review
34) Repeat step 16
--ALM Test Resource 4
35) Set Moderation State to Draft
36) Click Save.
37) Click My Workbench

EXPECTED RESULT:
Drafts
- [ ] Dataset 1
- [ ] Dataset 3
- [ ] Resource 1
- [ ] Resource 4

Needs Review
- [ ] Dataset 2
- [ ] Dataset 4
- [ ] Resource 2
- [ ] Resource 3

image
image


38) Log out
39) Log in as Content Editor
40) Click My Workbench
EXPECTED RESULT:
Drafts
- [ ] Dataset 1
- [ ] Dataset 3
- [ ] Resource 1
- [ ] Resource 4

Needs Review
- [ ] Dataset 2
- [ ] Dataset 4
- [ ] Resource 2
- [ ] Resource 3

41) Only two tabs available to me. I think this is because of permissions cleanup Willie mentioned.
42) Click "Needs Review"
image

**Pull request closed without merging**
