### PR TITLE
NuCivic/internal#703 As a Data Contributor, Content Editor and Portal Administrator I want to see easier to understand workbench lists

### PR DESCRIPTION
**Pull request by rhabbachi**
Prototype done for NuCivic/internal#703

* Display datasets and related referenced resources in an accordion style instead of table in admin/workbench/needs-review page.

This is for prototyping purpose only and needs to be discussed to define better specs.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://703_prototype.datastarter.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://703_prototype.datastarter.qa.nuamsdev.com

**Comment by rhabbachi** [comment]
needs_review_screen

More work done on the prototype:
* Removed problematic moderation_state and moderation_states_links fields. Adding this field to the resources view duplicates all the rows.
* Adding bulk operation on the resources view. As stated before, this is currently not working and redirects to the home page on each combination tried.

**Comment by nucivicmachine** [comment]
QA site created: http://703_prototype.datastarter.qa.nuamsdev.com

**Pull request merged**
