### PR TITLE
Copying hss theme to data_starter

### PR DESCRIPTION
**Pull request by drkloc**
NuCivic/nucivic-internal#561

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by drkloc** [comment]
Work in progress. Don't merge

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://upgrading_data_theme_to_radix.datastarter.qa.nuamsdev.com

**Pull request merged**
