### PR TITLE
NuCivic/internal#645: Behat tests for My Workbench page

### PR DESCRIPTION
**Pull request by SalahMessaoud**
- Tests for portal administrator and content editor role specified in NuCivic/internal#645

Not sure if we should add the @wip tag to the those tests. We need your input in this.

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Comment by frankcarey** [comment]
@SalahMessaoud  `@wip` is for "Work-In-Progress", basically meaning the test is broken and won't be run by default. If it's not broken, then you don't need to add that.

**Comment by acouch** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Pull request merged**
