### PR TITLE
NuCivic/internal#649 Improved Behat test

### PR DESCRIPTION
**Pull request by SalahMessaoud**
Cleaning up and refactoring behat tests

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Comment by wardmarzouki** [comment]
Starting to test for https://github.com/NuCivic/internal/issues/649

**Comment by wardmarzouki** [comment]
Behat test failed, tomorrow we will try test from salah machine because they are work on riadh machine

**Comment by nucivicmachine** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://master.datastarter.qa.nuamsdev.com

**Pull request merged**
